---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secrets
  namespace: k3s-ds-learn
spec:
  encryptedData:
    DB_PASS: AgAPttZ4N5BRJSkLciK82jPYEqzodHBpL5oqvY1GWjLxesfKpgePufOWf42yf/fcvL1zqaoF58n2pY3qEY13TyzxtnqCJT6SSrF4/Qs9jg9o/e0UZDwHB8+wvzHbMgs/h9B8oMoh7qoUjRqGDhm4Y9h5b7tQJMwq9b+z3w1LvvM8uJ0P1PdXA4545wfT1n+Pr1OdAhScfj1kXgsCjSAjLUUNAysIh2nNeLHTWoeLP/z8FQTINOBhgVtTHuP4r+mcC3bhezOCoflX+0d9Q7YOr326Y3ULtXAlI/+C1CBFUdaSm3LtA8Tg8iwh+U0tv9TkiVToXSHMqd++nKCmkGNaIbmHN9rAkcL0fxUDpdiHAW9BI9cs+jXO3mNWqThSBZgLmauZKVpwEtACWvOMsITF9niDiBOR4lkRu9CDqN3sfriJ7BEDC4Bs7+CbJ/smskuH2Io1ecN6kUj0cXIWYcOGve0KkhpSoV+q3yw31UxJCOriAHlrCDQdAfVdWr/3Rc1YYxVJ5VfakVbuMRMJOYLjOcYwWYlNEnnqHpYwohUFOISIB9GNxdkoUG5jH/CCB14lN66L0IjMHzzCt3pF8luNAI4Gxdcq006N9HLJ9cnFQVKXji5PjKj8X5JTkb2W6EZ2A/HiedX02a+ObeYUY4uN+jyiYve0Zfppnlt3GpNbhXEGLIZMuGpJbnh/zgOo0FpKpjIOUV9o4wYNwfdVQStnl0G/1ah+5gsn7HznYBgp5DC16Wsk+GbQ215djlBXrof003uQVVnt5ywBdLuKE05vk2/9
    DB_USER: AgCWGlcGW8ZA6/ZAUvwl851We4EeDSMHBTO0h+k/5/zpLDWsBuCpdnwvafThgEXDgDCIuA8fnlQX8rz3c+0K90SpqxD4ez490tB6y1kHW45TJ73ET8FzJGPt3E+bWqw9pI4quG2EUI+w+8/sudppx0YeR/3Tg3M3f/eFEFkPGRK0+y2/3RMR/3RHXUfh9BZVV2UtkRAXoN8I5G0x/6vIWl304OEa2wcLFpbOzZn0ZKco9zOFHXt/4rlza0DG3RkWqczkFmjzm3N5HZ2KJvEoONZ3IM+KbSwrhWFD7SUIdYwxCPCHDeUmd0C5fjcFQ26a2PB9s9iogwaiUfzQZ3mKUJ1dd4JnCkWLgRP45acWbgVYc4AtfGeZLN0QsyGfB5JRf12LzePBWLPmdUtkdp2jrK73zFfrKZZZOwiPZOcYo1WzBvRrNqTiMYOY6CpJfRQjH8aNUhYv3UEo1mdS1qJcBIpDYepqXNNNsEN67k0LDSe9rpuw3gaJ8nxX9h2lmMlV2nAiwEDeuef441csjzIKxeduLsohvNSsyQVD/kfi6ya0g0U+5jUXruFsx4ObZRYZLDs8HEVXWOtdFriwWrrTNJOriW6o8ffYj/LqUMqZGUlmMHRYtOxdLQLaeVaCfIWL2aemIEueW+q9438nAg3Ml8YkBslkceVmT0g05oZ16PPPW7QZpthemD7fWe7CP9uwPrc/o4r1O9k/rIXpbg==
  template:
    metadata:
      name: app-secrets
      namespace: k3s-ds-learn
