apiVersion: v1
kind: Service
metadata:
  name: app-api
  labels:
    app.kubernetes.io/name: app-api
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: app-api
  ports:
    - name: http
      port: 80
      targetPort: http
